In [ ]:
import tensorflow as tf

# scalar: rank 0 (dimensions or axis)
scalar = tf.constant(3, dtype=tf.float32)
print(scalar)

# vector: rank 1
vector = tf.constant([1, 2, 3])
print(vector)

# matrix (rank 2)
matrix = tf.constant([[1, 2, 3], [3, 4, 5]])
print(matrix)

# RGB images
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(tensor)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
import numpy as np

scores = np.array([1, 2, 3])
print(scores)

tensor = tf.constant(scores, dtype=tf.float32)
print(tensor)

print(tensor.numpy())

[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [ ]:
# more ways of generating tensors
tensor = tf.zeros(shape=(2, 3))
print(tensor)

tensor = tf.ones(shape=(3, 2))
print(tensor)

tensor = tf.fill(dims=(4, 4), value=5.4)
print(tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[5.4 5.4 5.4 5.4]
 [5.4 5.4 5.4 5.4]
 [5.4 5.4 5.4 5.4]
 [5.4 5.4 5.4 5.4]], shape=(4, 4), dtype=float32)


In [ ]:
# Generating random tensors
random_tensor = tf.random.normal(shape=(3, 2))
print(random_tensor)

tf.random.uniform(shape=(2, 3), minval=0, maxval=1)

tf.Tensor(
[[-1.546566  -1.0661956]
 [-0.5551627  1.3533537]
 [-1.723057   0.5379029]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.50391066, 0.5950817 , 0.488055  ],
       [0.51936257, 0.07977509, 0.2538581 ]], dtype=float32)>

In [ ]:
# math operations
a = tf.constant([1, 2, 3], dtype=tf.float32)
b = tf.constant([4, 5, 6], dtype=tf.float32)

# add
c = tf.add(a, b)
c

c = tf.subtract(a, b)
c

# element-wise multiplication
c = tf.multiply(a, b)
c

# Matrix Multiplication (dot product)
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
c = tf.matmul(a, b)
print(c.numpy())

[[19. 22.]
 [43. 50.]]


In [ ]:
# accessing elements of a tensor
tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)
tensor.shape

print(tensor[:, 1])

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [ ]:
# Reshape tensors
tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)
print(tensor.shape)

# reshape to (2, 3)
reshaped_tensor = tf.reshape(tensor, shape=(2, 3))
print(reshaped_tensor)

vector = tf.constant([1, 2, 3], dtype=tf.float32)
print(vector.shape)
matrix = tf.reshape(vector, shape=(3, 1))
print(matrix)

(3, 2)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(3,)
tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float32)
